config/routes.rb
Rails.application.routes.draw do
  get "home/index"
  get 'relatorios/clientes_dashboard', to: 'relatorios#clientes_dashboard'
  devise_for :users
  
  resources :clientes
  resources :produtos
  resources :pedidos
  resources :relatorios

  # Página inicial
  root 'home#index'

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root # Página inicial para usuários logados
  end

  unauthenticated do
    root to: 'devise/sessions#new', as: :unauthenticated_root # Página inicial para não logados (login)
  end

  namespace :api do
    namespace :v1 do
      resources :clientes, only: [:index, :show, :create]
      resources :produtos, only: [:index, :show]
    end
  end
end

app/models/pedido.rb
class Pedido < ApplicationRecord
  belongs_to :cliente
  belongs_to :produto
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy!

    respond_to do |format|
      format.html { redirect_to pedidos_path, status: :see_other, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:cliente_id, :produto_id, :quantidade)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :cliente_id, style: "display: block" %>
    <%= form.text_field :cliente_id %>
  </div>

  <div>
    <%= form.label :produto_id, style: "display: block" %>
    <%= form.text_field :produto_id %>
  </div>

  <div>
    <%= form.label :quantidade, style: "display: block" %>
    <%= form.number_field :quantidade %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Cliente:</strong>
    <%= pedido.cliente_id %>
  </p>

  <p>
    <strong>Produto:</strong>
    <%= pedido.produto_id %>
  </p>

  <p>
    <strong>Quantidade:</strong>
    <%= pedido.quantidade %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<% content_for :title, "Editing pedido" %>

<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pedidos" %>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>

app/views/pedidos/new.html.erb
<% content_for :title, "New pedido" %>

<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>